module.exports = [
  
  { id: 1,
    name: "Eddard Stark",
    img: "got_imgs/eddardstark.jpeg",
    house: {name:"Stark", words:"Winter is coming", sigil:"DireWolf"},
    title: [true, "Warden of the North"],
    hair: "brown",
    sex: "male",
    isAlive: false,
  },
  { id: 2,
    name: "John Snow",
    img: "got_imgs/jonsnow.jpeg",
    house: {name:"Stark", words:"Winter is coming", sigil:"DireWolf"},
    title: [false],
    hair: "black",
    sex: "male",
    isAlive: true,
  },
  { id: 3,
    name: "Arya Stark",
    img: "got_imgs/aryastark.jpeg",
    house: {name:"Stark", words:"Winter is coming", sigil:"DireWolf"},
    title: [false],
    hair: "black",
    sex: "female",
    isAlive: true,
  },
  { id: 4,
    name: "Tyrion Lannister",
    img: "got_imgs/tyrion.jpeg",
    house: {name:"Lannister", words:"Hear me Roar", sigil:"Lion"},
    title: [true, "The Imp"],
    hair: "Blonde",
    sex: "male",
    isAlive: true,
  },
  { id: 5,
    name: "Jaime Lannister",
    img: "got_imgs/jaime.jpeg",
    house: {name:"Lannister", words:"Hear me Roar", sigil:"Lion"},
    title: [true, "Kingslayer"],
    hair: "Blonde",
    sex: "male",
    isAlive: true,
  },
  { id: 6,
    name: "Cersei Lannister",
    img: "got_imgs/cersei.jpeg",
    house: {name:"Lannister", words:"Hear me Roar", sigil:"Lion"},
    title: [true, "The Imp"],
    hair: "Blonde",
    sex: "female",
    isAlive: true,
  },
  { id: 7,
    name: "Theon Greyjoy",
    img: "got_imgs/Theon.jpeg",
    house: {name:"Greyjoy", words:"We Do Not Sow", sigil:"Kraken"},
    title: [true, "Reek"],
    hair: "Brown",
    sex: "male",
    isAlive: true,
  },
  { id: 8,
    name: "Tywin Lannister",
    img: "got_imgs/tywin.jpeg",
    house: {name:"Lannister", words:"Hear me Roar", sigil:"Lion"},
    title: [true, "Warden of the West"],
    hair: "Blonde",
    sex: "male",
    isAlive: false,
  },
  { id: 9,
    name: "Sandor Clegane",
    img: "got_imgs/thehound.jpeg",
    house: {name:"Clegane", words:"Sworn to Lannister", sigil:"3 Dogs"},
    title: [true, "The Hound"],
    hair: "Black",
    sex: "male",
    isAlive: true,
  },
  { id: 10,
    name: "Robert Barratheon",
    img: "got_imgs/robert.jpeg",
    house: {name:"Barratheon", words:"Ours is the Fury", sigil:"Stag"},
    title: [true, "King"],
    hair: "Black",
    sex: "male",
    isAlive: false,
  },
  { id: 11,
    name: "Jeoffrey Barratheon",
    img: "got_imgs/joffrey.jpeg",
    house: {name:"Barratheon", words:"Ours is the Fury", sigil:"Stag"},
    title: [true, "King"],
    hair: "Blonde",
    sex: "male",
    isAlive: false,
  },
  { id: 12,
    name: "Daenerys Targaryen",
    img: "got_imgs/dany.jpeg",
    house: {name:"Targaryen", words:"Fire and Blood", sigil:"Three Headed Dragon"},
    title: [true, "The Unburnt Queen of the Andals, the Rhoynar, and of the First Men, Queen of Meereen, Khaleesi of the Great Grass Sea, Breaker of Chains, Mother of Dragons"],
    hair: "White",
    sex: "female",
    isAlive: true,
  }
]
